### ISSUE TITLE
Change line comment value in config to enable VSCode comment shortcut

### ISSUE THREAD

**Issue by ashtonomy** [VisualText/vscode-nlp#611]
In ```nlp-configuration.json```, line 3, line comment is defined as ```\\```, whereas NLP++ uses ```#``` as a line comment. This is preventing users from utilizing VSCode's comment shortcut ```ctrl + \```.
```json
"comments": {
	"lineComment": "//",
	"blockComment": [ "/*", "*/" ]
},
```
I'm not sure if there are other dependencies here; I have been making this change locally with no issues, but it gets overwritten with each update.

**Comment by dehilsterlexis** [comment]
@ashtonomy , I'm not following the fix. I'm not familiar with `ctr + \`

**Comment by ashtonomy** [comment]
VSCode natively supports `ctrl + \` as a shortcut for commenting out blocks of code. So, for example, you can highlight a block of code and press `ctrl + \` to add line comments to each line. You can also use the same key binding to comment out the entire line at which your text cursor is placed, regardless of its location in the line. 

You could, of course, just use a multi-line comment or right click and choose comment, but for those of us who grown used to it, it's hard to switch back. Thanks!

[More info here.](https://vscode.one/comment-vscode/)
