### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by 4n506g** [VisualText/vscode-nlp#758]
Hi,

I'm seeing an issue with the extension failing to load in vscode on Windows 10. I'm using the latest version available.

I get the following error:

[error] Error: ENOENT: no such file or directory, copyfile 'c:\Users\localadmin\.vscode\extensions\dehilster.nlp-2.17.1\.vscode\state.json' -> '\analyzers\.vscode\state.json'

I have checked the filesystem and whilst the directory exists the state.json file does not exist....

**Comment by 4n506g** [comment]
I managed to get around this by just creating a blank state.json file in the above directory, but now I get another error saying

"[error] Error: Unable to write to User Settings because analyzer.directory is not a registered configuration."

**Comment by dehilsterlexis** [comment]
This is actually a benign but somewhat annoying problem. I don't think it this affects the functionality. Does it?

**Comment by 4n506g** [comment]
The only thing I think it seems to mean is that the example analyzers won’t load. At least I can’t get them to.

**Comment by dehilsterlexis** [comment]
Are you clicking on the gear in the analyzer view list?

**Comment by dehilsterlexis** [comment]
@4n506g I believe this is fixed with the new updates of the nlp engline and VisualText.

**Comment by dehilsterlexis** [comment]
@4n506g I'm closing this unless you see any more problems.
