### ISSUE TITLE
Moving pass up/down focus

### ISSUE THREAD

**Issue by amnonma** [VisualText/vscode-nlp#795]
Moving a pass up/down in the analyzer sequence, I expect to keep selecting and moving the SAME PASS repeatedly.
I'm always shocked when I move it and then I'm no longer selecting it.
Low priority.
@dehilsterlexis

**Comment by dehilsterlexis** [comment]
@amnonma unfortunately, we're not given any of those types of controls for the tree widget. I try to do my best given the high number of restrictions for these widgets for writing language extensions for VSCode.
