### ISSUE TITLE
Reformat rule

### ISSUE THREAD

**Issue by amnonma** [VisualText/vscode-nlp#817]
@dehilsterlexis 
(Don't know if this is a re-submit)
Looks like tabs become 2 spaces, formatting is wrong, eg for this rule.

# over speed limit
@CHECK
  if (!N(5) && !N(7)) fail();
@POST
AddClass(X(2),"speed");
++S("plus");
single();
@RULES
_overLimit <-
  _xWILD [one match=(_over _above over ovr)]	### (1)
  _xWILD [max=2]								### (2)
  _xWILD [opt match=(_the the)]				### (3)
  _xWILD [max=2]								### (4)
  _xWILD [opt match=(_speed spd sp)]			### (5)
  _xPUNCT [star]								### (6)
  _xWILD [opt match=(_limit)]					### (7)
	@@

**Comment by dehilsterlexis** [comment]
@amnonma yea. Been that way for a while. I have tried to fix this numerous times. Still haven't succeeded.
