### ISSUE TITLE
Comment a whole line

### ISSUE THREAD

**Issue by amnonma** [VisualText/vscode-nlp#828]
@dehilsterlexis 
When Comment Line is used and whole lines are selected, the line beyond is also commented out.
Understood that's where the cursor sits, but it is not what is intended in those cases.
Have to backtrack one character in order to get the desired commenting.

**Comment by dehilsterlexis** [comment]
@amnonma it is always recommended to use ctrl-/ for commenting anything in the VSCode editor. Perhaps I will remove the "Comment Line".
