### ISSUE TITLE
New TextView broken

### ISSUE THREAD

**Issue by amnonma** [VisualText/vscode-nlp#831]
@dehilsterlexis 
Can't see any files or folders.  Can't get them from explorer popup.

Cannot find module 'moment'
Require stack:
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\textView.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\analyzerView.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\fileOps.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\sequenceView.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\nlp.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\treeFile.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\sequence.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\analyzer.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\visualText.js
- c:\Users\amnon\.vscode\extensions\dehilster.nlp-2.25.1\dist\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
-

**Comment by dehilsterlexis** [comment]
@amnonma I forgot to include a new npm package.

**Comment by amnonma** [comment]
@dehilsterlexis 
Still not seeing that module.
Back to a prior NLP++ version (2.24.4) for now.

**Comment by dehilsterlexis** [comment]
@amnonma almost fixed

**Comment by dehilsterlexis** [comment]
@amnonma try it now (version 2.25.6)

**Comment by amnonma** [comment]
@dehilsterlexis 
Ok, 2.25.6 looking good, thx.

**Comment by dehilsterlexis** [comment]
@amnonma that is the tradeoff. To do what you want, would take making a background process and keeping a separate file. You can turn it off or on for now. VSCode does not allow for the updating of a single node in the treeview. It's pretty limited and wonky for large trees.

**Comment by dehilsterlexis** [comment]
@amnonma fixed
