### ISSUE TITLE
NLP++ Reformat rule

### ISSUE THREAD

**Issue by Kruthika-21** [VisualText/vscode-nlp#838]
The Reformat rule option splits the text up and the rules are becoming unclear

**Comment by dehilsterlexis** [comment]
@Kruthika-21 you need to give a specific example here that is not working. Thanks!

**Comment by Kruthika-21** [comment]
This is one instance where it fails:
Initial:
![image](https://github.com/VisualText/vscode-nlp/assets/78919646/b5526a3e-7b8c-4273-8239-9721be56df1b)
After:
![image](https://github.com/VisualText/vscode-nlp/assets/78919646/95fb760c-3720-4a03-a0ae-4eabfec9dafa)

**Comment by dehilsterlexis** [comment]
Could you put this in the github issue please?

https://github.com/VisualText/vscode-nlp/issues/838

Thanks!

David

**Comment by dehilsterlexis** [comment]
Kruthika:

I see you already have done that! Sorry! I read my email first.

Thanks so much!!!

David
